name: Publish

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - '/integration/*'
      - 'package*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Bootstrap
        run: npm ci

      - name: Lib Tests
        run: npx lerna run test

      - name: Build Integration (Own)
        run: npx tsc -p integration/own && npx vite build integration/own

      - name: Build Integration (Mixed)
        run: npx tsc -p integration/mixed && npx vite build integration/mixed

      - name: Publish
        run: npx lerna publish --canary --preid canary.$(date +"%s") --dist-tag canary --yes
